# Autogenerated by configen, do not edit.
# If encountering an error, please file an issue @
# https://github.com/romesco/quadsim
# fmt: off
# isort: skip_file
# flake8: noqa
# Hydra + Quadsim 

from dataclasses import dataclass, field
from omegaconf import MISSING
from typing import Any
from typing import List


@dataclass
class A1Conf:
    _target_: str = "quadsim.robots.a1.A1"
    pybullet_client: Any = MISSING
    motors: Any = MISSING  # List[Motor]
    sensors: Any = MISSING  # List[Sensor]
    urdf_path: str = "a1/a1.urdf"
    base_link_names: List[str] = field(default_factory=lambda: ['trunk'])
    motor_joint_names: List[str] = field(default_factory=lambda: ['FR_hip_joint', 'FR_upper_joint', 'FR_lower_joint', 'FL_hip_joint', 'FL_upper_joint', 'FL_lower_joint', 'RR_hip_joint', 'RR_upper_joint', 'RR_lower_joint', 'RL_hip_joint', 'RL_upper_joint', 'RL_lower_joint'])
    init_motor_angles: List[float] = field(default_factory=lambda: [0.0, 0.9, -1.8, 0.0, 0.9, -1.8, 0.0, 0.9, -1.8, 0.0, 0.9, -1.8])
    foot_link_names: List[str] = field(default_factory=lambda: ['FR_toe', 'FL_toe', 'RR_toe', 'RL_toe'])
    on_rack: bool = False
