# Autogenerated by configen, do not edit.
# If encountering an error, please file an issue @
# https://github.com/romesco/quadsim
# fmt: off
# isort: skip_file
# flake8: noqa
# Hydra + Quadsim 

from dataclasses import dataclass, field
from omegaconf import MISSING
from quadsim.robots.motors import MotorControlMode
from typing import Any


@dataclass
class MotorModelConf:
    _target_: str = "quadsim.robots.motors.MotorModel"
    name: str = "None"
    motor_control_mode: MotorControlMode = MotorControlMode.POSITION
    init_position: float = 0.0
    min_position: float = 0.0
    max_position: float = 0.0
    min_velocity: float = 0.0
    max_velocity: float = 0.0
    min_torque: float = 0.0
    max_torque: float = 0.0
    kp: float = 0.0
    kd: float = 0.0


@dataclass
class MotorGroupConf:
    _target_: str = "quadsim.robots.motors.MotorGroup"
    motors: Any = MISSING  # Tuple[MotorModel, ...]
