# Autogenerated by configen, do not edit.
# If encountering an error, please file an issue @
# https://github.com/romesco/quadsim
# fmt: off
# isort: skip_file
# flake8: noqa
# Hydra + Quadsim
from dataclasses import dataclass
from dataclasses import field
from typing import Any
from typing import Tuple

from omegaconf import MISSING


@dataclass
class RobotConf:
    _target_: str = "quadsim.robots.robot.Robot"
    pybullet_client: Any = MISSING
    motors: Any = MISSING  # List[Motor]
    sensors: Any = MISSING  # List[Sensor]
    urdf_path: str = MISSING
    base_link_names: Tuple[str] = MISSING
    motor_joint_names: Tuple[str] = MISSING
    init_motor_angles: Tuple[float] = MISSING
    foot_link_names: Tuple[str] = MISSING
    on_rack: bool = MISSING
