# Autogenerated by configen, do not edit.
# If encountering an error, please file an issue @
# https://github.com/romesco/quadsim
# fmt: off
# isort: skip_file
# flake8: noqa
# Hydra + Quadsim 

from dataclasses import dataclass, field
from omegaconf import MISSING
from typing import Any
from typing import List


@dataclass
class RobotConf:
    _target_: str = "quadsim.robots.robot.Robot"
    pybullet_client: Any = MISSING
    motors: Any = MISSING  # List[Motor]
    sensors: Any = MISSING  # List[Sensor]
    urdf_path: str = MISSING
    base_link_names: List[str] = MISSING
    motor_joint_names: List[str] = MISSING
    init_motor_angles: List[float] = MISSING
    foot_link_names: List[str] = MISSING
    on_rack: bool = MISSING
